### ISSUE TITLE
Only works on linux - I need submodules for Windows

### ISSUE THREAD

**Issue by tig** [textbook/git-checkout-submodule-action#7]
Any suggestions on how to make this work would be appreciated.

Just learning how to use Github actions/yaml/etc... so go easy.

![image](https://user-images.githubusercontent.com/585482/80933437-f9882180-8d80-11ea-9256-c56ef0644c96.png)

**Comment by carueda** [comment]
Just hit this same issue, in my case with a macos-latest target 
![image](https://user-images.githubusercontent.com/556505/82102762-64acee80-96c5-11ea-8b0a-e26ffef22563.png)

**Comment by carueda** [comment]
Well, just tried srt32/git-actions@v0.0.3 as [suggested](https://github.com/marketplace/actions/checkout-submodules)), with same error, then came across https://github.community/t5/GitHub-Actions/Container-based-actions-from-Mac-and-Windows/td-p/37471

**Comment by carueda** [comment]
@tig Here's a solution (workaround) that I'm now using:

Basically:
- use a linux-based job (`grab_code` below) to do the checkout including submodules, and "upload" all the source directory (using `actions/upload-artifact`)
- make your windows-based job depend (`needs`) on `grab_code` to grab the source code (using `actions/download-artifact`) and from there, do whatever you need.

```
jobs:
  grab_code:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: textbook/git-checkout-submodule-action@2.1.1

    - uses: actions/upload-artifact@v2
      with:
        name: my-whole-src
        path: ./

  my_windows_stuff:
    needs: grab_code
    runs-on: windows

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: my-whole-src
    - ...
```
