### ISSUE TITLE
Access rights to private repositories

### ISSUE THREAD

**Issue by chrisbjr** [textbook/git-checkout-submodule-action#8]
Is there a way here to define any sort of token to be able to clone private repos?

**Comment by dastasoft** [comment]
Same issue here

**Comment by sGambolati** [comment]
Same question here!

**Comment by individual11** [comment]
same here

**Comment by martindur** [comment]
Same issue

**Comment by abronin** [comment]
Same for me

**Comment by Atinlay** [comment]
Same here

**Comment by chrisbjr** [comment]
FYI, we were able to checkout submodules using Github Actions checkout. Here is a sample step:

```
steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: true
```

The access token can be defined in the Action Secrets of your repository.
