### ISSUE TITLE
fatal: not a git repository (or any parent up to mount point /github)

### ISSUE THREAD

**Issue by mdeuerlein** [textbook/git-checkout-submodule-action#9]
Running as GitAction I'm getting this error:
`fatal: not a git repository (or any parent up to mount point /github)`

**My workflow.yaml**
```
name: Update on Push
on: [push]

jobs:
  update: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout submodules
        uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive
```
